#markdown: kramdown

# For related posts
# lsi: true
# highlighter: pygments

permalink: pretty
paginate: 5
paginate_path: "news/page:num"

safe: true

title: The STAR Lab
subtitle: Spatiotemporal Pattern Analysis & Research 
author: Guofeng Cao 
production_url: http://www.depts.ttu.edu/geospatial/starlab
url: http://www.depts.ttu.edu/geospatial/starlab
