#markdown: kramdown

# For related posts
# lsi: true
# highlighter: pygments

permalink: pretty
paginate: 5
paginate_path: "news/page:num"

safe: true

title: STAR Lab
subtitle: Spatiotemporal Pattern Analysis & Research Laboratory
author: Guofeng Cao 
production_url: http://www.spatial.ttu.edu
url: 
